#!/bin/sh

cleanup () {
  unset -f die cleanup
  unset install_dir
}
die () { echo "$@" ; cleanup ; exit 1; }

F1_ENV=testing \. ../../install.sh
HOME="__home__"

# F1_DIR is set
F1_DIR="some_dir"
install_dir=$(f1_install_dir)
[ "_$install_dir" = "_$F1_DIR" ] || die "f1_install_dir should use \$F1_DIR if it exists. Current output: $install_dir"

unset F1_DIR

# F1_DIR is not set
install_dir=$(f1_install_dir)
[ "_$install_dir" = "_$HOME/.f1" ] || die "f1_install_dir should default to \$HOME/.f1. Current output: $install_dir"

cleanup
