#

include:
  - /base_azure_db_stage.yml
  - /base_create_namespace_stage.yml
  - /base_delete_useless_k8s_ns_stage.yml
  - /base_deploy_app_chart_stage.yml
  - /base_deploy_kosko_stage.yml
  - /base_docker_helm_image_stage.yml
  - /base_docker_kubectl_image_stage.yml
  - /base_notify_github_stage.yml
  - /base_register_stage.yml
  - /base_semantic_release_stage.yml
  - /base_trigger_stage.yml
  - /base_yarn_stage.yml

#

stages:
  - Install
  - Code Quality
  - Registration
  - Release
  - Deploy

#

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 5
  #
  # To activate the auto release
  # AUTO_DEVOPS_RELEASE_AUTO: true

#
#
#

.production_rule: &autodevops_production_rule
  if: "$PRODUCTION && $CI_COMMIT_TAG"
.trigger_rule: &autodevops_trigger_rule
  if: "$PRODUCTION || $RELEASE"

.autodevops_base_rules:
  rules:
    - &autodevops_global_skip_case
      <<: &autodevops_trigger_rule
      when: never
    - when: on_success

#
#
#

.autodevops_trigger_release:
  extends:
    - .base_trigger_release_stage
    - .autodevops_base_rules
  stage: Install
  rules:
    - <<: *autodevops_global_skip_case
    - if: "$AUTO_DEVOPS_RELEASE_AUTO"
      when: always
    - when: manual

Trigger Release:
  extends: .autodevops_trigger_release

.autodevops_release:
  extends:
    - .base_semantic_release_stage
    - .autodevops_base_rules
  rules:
    - if: "$RELEASE"
  variables:
    GIT_DEPTH: 4242
    SEMANTIC_RELEASE_ARGS: "--dry-run"
  stage: Release

Release:
  extends: .autodevops_release

#

.autodevops_trigger_production:
  stage: .post
  rules:
    - if: "$CI_COMMIT_TAG"
  extends: .base_trigger_production_stage

Trigger Production:
  extends: .autodevops_trigger_production

#

.autodevops_install:
  extends:
    - .base_yarn
    - .autodevops_base_rules
  interruptible: true

Install:
  extends:
    - .autodevops_install

#
#
#

#
#
#

.autodevops_lint:
  extends:
    - .base_yarn_script
    - .autodevops_base_rules
  needs:
    - job: Install
      artifacts: true
  script:
    - yarn lint

Lint:
  extends: .autodevops_lint

#

.autodevops_test:
  extends:
    - .base_yarn_script
    - .autodevops_base_rules
  needs:
    - job: Install
      artifacts: true
  script:
    - yarn test

Test:
  extends: .autodevops_test

#

.autodevops_build:
  extends:
    - .base_yarn_build_next
    - .autodevops_base_rules
  needs:
    - job: Install
      artifacts: true

Build:
  extends: .autodevops_build

#
#
#

#
#
#

.autodevops_register_image:
  extends:
    - .base_register_stage
    - .autodevops_base_rules
  stage: Registration
  needs:
    - job: Build
      artifacts: true
  variables:
    CONTEXT: .
    IMAGE_NAME: $CI_REGISTRY_IMAGE
Register image:
  extends: .autodevops_register_image

#
#
#

#
#
#

.deploy_stage:
  stage: Deploy
  extends:
    - .base_deploy_kosko_stage

#

Review:
  extends:
    - .autodevops_base_rules
    - .deploy_stage
  needs:
    - job: Register image
      artifacts: false
  variables:
    KOSKO_GENERATE_ARGS: >-
      --env dev
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev
    url: https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

Production:
  extends:
    - .deploy_stage
  rules:
    - <<: &autodevops_production_rule
  variables:
    KOSKO_GENERATE_ARGS: >-
      --env prod "!(_*)"
  environment:
    name: prod
    url: https://${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}

#

.autodevops_notify_starting_deployment:
  extends:
    - .base_notify_pending_stage
    - .autodevops_base_rules
  stage: Deploy
Notify Starting Deployment:
  extends: .autodevops_notify_starting_deployment

#

.notify_review:
  stage: .post
  dependencies:
    - Notify Starting Deployment
  environment:
    name: ${CI_COMMIT_REF_NAME}-dev
  before_script:
    - HOST="https://${CI_ENVIRONMENT_SLUG}-${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}"

.autodevops_notify_fail_review:
  extends:
    - .base_notify_fail_stage
    - .notify_review
  rules:
    - <<: *autodevops_global_skip_case
    - when: on_failure
Notify Fail (review):
  extends: .autodevops_notify_fail_review

.autodevops_notify_success_review:
  extends:
    - .base_notify_success_stage
    - .autodevops_base_rules
    - .notify_review
Notify Success (review):
  extends: .autodevops_notify_success_review

#

.notify_prod:
  stage: .post
  dependencies:
    - Notify Starting Deployment
  environment:
    name: prod
  before_script:
    - HOST="https://${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}"

.autodevops_notify_fail_prod:
  extends:
    - .base_notify_fail_stage
    - .notify_prod
  rules:
    - <<: &autodevops_production_rule
      when: on_failure
Notify Fail (prod):
  extends: .autodevops_notify_fail_prod

.autodevops_notify_success_prod:
  extends:
    - .base_notify_success_stage
    - .notify_prod
  rules:
    - <<: &autodevops_production_rule
      when: on_success
Notify Success (prod):
  extends: .autodevops_notify_success_prod
