#!/bin/sh

die () { echo "$@" ; cleanup ; exit 1; }
cleanup () {
  unset -f die cleanup
  unset actual expected
}

\. ../../../f1.sh

actual="$(f1 --help)"
expected="🏎️"

echo $actual |grep "$expected" || \
die "'--help' should display help message" \
  "expected '$expected', got '$actual'"

#

cleanup
